### ISSUE TITLE
cordova.plugins.hotspot.configureHotspot error

### ISSUE THREAD

**Issue by webmaster-imaginet** [hypery2k/cordova-hotspot-plugin#10]
This method returns error in errorCB
I try all the options as shown in the JAVA file (lowercase or uppercase)
![image](https://cloud.githubusercontent.com/assets/4920443/12701622/2435847e-c817-11e5-9853-28864aec7164.png)

The ERROR:
![image](https://cloud.githubusercontent.com/assets/4920443/12701614/e4b3bcf8-c816-11e5-8e9a-0db30a5566b2.png)

Sample code:
![image](https://cloud.githubusercontent.com/assets/4920443/12701635/8987ac8a-c817-11e5-9205-8d4ae87c234b.png)

**Comment by hypery2k** [comment]
should be fixed in 0.7.2
