### ISSUE TITLE
cordova.plugins.hotspot.createHotspot create only OPEN Hotspot

### ISSUE THREAD

**Issue by webmaster-imaginet** [hypery2k/cordova-hotspot-plugin#11]
This method create only "open" Hotspot
I try all the options as shown in the JAVA file (lowercase or uppercase)
![image](https://cloud.githubusercontent.com/assets/4920443/12701694/f1056f08-c819-11e5-918e-6fbfba8fb08d.png)

Code sample:
![image](https://cloud.githubusercontent.com/assets/4920443/12701687/c6ecfb50-c819-11e5-90ef-50ace980325c.png)

Log:
![image](https://cloud.githubusercontent.com/assets/4920443/12701683/b7caf2b2-c819-11e5-93e4-3a5eae5035f9.png)

Result:
![image](https://cloud.githubusercontent.com/assets/4920443/12701672/4ef1a9ca-c819-11e5-9dd7-90c81c72995e.png)

**Comment by hypery2k** [comment]
should be fixed in 0.7.2
