### ISSUE TITLE
Methods name change

### ISSUE THREAD

**Issue by webmaster-imaginet** [hypery2k/cordova-hotspot-plugin#12]
I think it will be better to change these methods name:
1. From "cordova.plugins.hotspot.connectToHotspot" to "**cordova.plugins.hotspot.connectToWifi**"
2. From "cordova.plugins.hotspot.startPeriodicallyScan" to "**cordova.plugins.hotspot.startWifiPeriodicallyScan**"
3. From "cordova.plugins.hotspot.stopPeriodicallyScan" to "**cordova.plugins.hotspot.stopWifiPeriodicallyScan**"

It will clarify that this methods are used for Wifi functionality.

**Comment by hypery2k** [comment]
will change with version 1.0.0
