### ISSUE TITLE
Ping Error Reply 

### ISSUE THREAD

**Issue by andrienpecson** [hypery2k/cordova-hotspot-plugin#13]
Is there any way I can do to detect DTU(Destination Timeout) or RTO (Request Timeout) in the plugin when using this plugin?

**Comment by hypery2k** [comment]
I've added a basic implementation for the results. But currently don't have much time for testing...
A newer release will not be available this week

**Comment by andrienpecson** [comment]
Sir,
Can I test it to help you? Thanks

**Comment by hypery2k** [comment]
You can the plugin from GitHub directly:

``` shell
 cordova plugin add https://github.com/hypery2k/cordova-hotspot-plugin.git
```

Sample output looks like this:
for success:

``` javascript
{  
   "requestTimeout":false,
   "stat":{  
      "packetLoss":"0",
      "time":"9009",
      "min":"12.361",
      "max":"624.630",
      "avg":"127.389",
      "stddev":"199.526"
   }
}
```

for error

``` javascript
{  
   "requestTimeout":false,
   "stat":{  
      "packetLoss":"100",
      "time":"9002"
   }
}
```

**Comment by andrienpecson** [comment]
Thank you sir.

Sir What would be the result if DHU or RTO?

I'm also getting this error Sir 
Error in Success callbackId: HotSpotPlugin884672193 : TypeError: Cannot read property '1' of null cordova.js:310
Uncaught TypeError: Cannot read property '1' of null

every time I ping a DHU website

**Comment by andrienpecson** [comment]
I'm getting this error Sir 
Error in Success callbackId: HotSpotPlugin884672193 : TypeError: Cannot read property '1' of null cordova.js:310
Uncaught TypeError: Cannot read property '1' of null

**Comment by hypery2k** [comment]
Can you please try again with latest Master and provide complete error stack?

**Comment by andrienpecson** [comment]
![image](https://cloud.githubusercontent.com/assets/13114319/13105322/a1a8ef84-d59d-11e5-8f96-b00cbc805b97.png)

I already get the latest Master Sir.

**Comment by andrienpecson** [comment]
I checked on the code sir. Its on the response parameter of the parseResponse function. Everytime the response is OK it does not satisfy the .match()

**Comment by hypery2k** [comment]
mmmh ok, can you please past the raw response before it's passing to the parseResponse function via javascript breakpoint?
I will try to add some test cases for that

**Comment by andrienpecson** [comment]
Sir the response before passing to the parseResponse is 'Class not found' it fall under the error callback of the cordova.exec function.

**Comment by hypery2k** [comment]
can you please post the message here?

**Comment by andrienpecson** [comment]
what message sir?

**Comment by hypery2k** [comment]
The error response message

**Comment by andrienpecson** [comment]
'Class not found'

**Comment by andrienpecson** [comment]
Class not found

**Comment by hypery2k** [comment]
mmmh I've got no idea what's wrong. Which cordova version are you using? Which Android version are you using?

**Comment by andrienpecson** [comment]
Installed platforms: **android 4.1.1**
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, webos, windows, windows8, wp8
cordova: **5.3.1**
I used this plugin in ionic framework

To duplicate this error Sir try to ping an unreachable ip.

**Comment by hypery2k** [comment]
when using this line 

``` javascript
cordova.plugins.hotspot.pingHost('118.8.8.118', function(res){console.log(res);}, function(err){console.error(JSON.stringify(err));})
```

I'm getting this with android 4.0.3:

``` javascript
{"requestTimeout":false,"stat":{"packetLoss":"100","time":"8999"}}
```

**Comment by andrienpecson** [comment]
maybe on the version of the android Sir

**Comment by hypery2k** [comment]
the supported API Level 19 means Android 4.4+ 
Maybe thats the issue
