### ISSUE TITLE
function toggleWifi error

### ISSUE THREAD

**Issue by cccoba** [hypery2k/cordova-hotspot-plugin#14]
Hello. I really liked your plugin. thank you

but, if i use function cordova.plugins.hotspot.toggleWifi
`cordova.plugins.hotspot.toggleWifi(
   function (isActive) {
       alert('wifi is on');
   },function (err) {
       alert('error');
   }
);`
my Android Device Monitor say
`Uncaught ReferenceError: successCB is not defined at file:///android_asset/www/cordova.js:312
`
and function is executed (wifi is toggled) without my alert

P.S. you are planning to add more function to support  Wifi Direct?
P.P.S. sorry for my English

**Comment by LuisAlmeidaIST** [comment]
Hi there,

this issue is still not fixed.

```
cordova.plugins.hotspot.toggleWifi(function(start){
                                    alert("Sucess!");
                                    isWifiOn=start;
                                    }, 
                                   function(start){
                                    alert(start);
                                    isWifiOn=start;
                                    })
```

Executing this I get and alert saying "Invalid Action" and the Wifi is turned-on, if i execute it again while the wifi is On, it gets turned off and the same alert with the same error pops up.

Can you look into it again please?
