### ISSUE TITLE
configureHotspot error

### ISSUE THREAD

**Issue by cccoba** [hypery2k/cordova-hotspot-plugin#15]
Hello.

when i create hotspot with 
`cordova.plugins.hotspot.createHotspot(ssid, mode, password, 
    function () {
       alert('Hotspot is created');
    },function () {
        alert('Error');
    }
);`
if hotspot already is started = good
if hotspot not started = hotspot name have a previous name

i want if before start hotspot configarate my hotspot. but if i run configurate function
`cordova.plugins.hotspot.configureHotspot(ssid, mode, password, 
       function () {
           alert('Hotspot is configured ');
       },function () {
          alert('Error');
       }
   );`

function return alert('Error');

**Comment by cccoba** [comment]
Name hotspot not changed if wifi is enabled (function createHotspot)

**Comment by sankar4n** [comment]
Same issue here.

**Comment by hypery2k** [comment]
will be fixed in version 1.0.0

**Comment by sankar4n** [comment]
Hi @hypery2k, Thanks for the quick fix. Look forward for the v1.0.0 release :)

**Comment by sankar4n** [comment]
That was quick! 1.0.0 is already out. Thank you very much for the great help.
