### ISSUE TITLE
function scanWifi

### ISSUE THREAD

**Issue by cccoba** [hypery2k/cordova-hotspot-plugin#16]
if my _huawei g750 (4.2.2)_ function cordova.plugins.hotspot.**scanWifi** and cordova.plugins.hotspot.**scanWifiByLevel**
working fine,
but my othet phone _Fly iq449 (4.1.2)_ this functions not return result (listOfNetworks)
`cordova.plugins.hotspot.scanWifi( 
   function (listOfNetworks) {
console.log(listOfNetworks);
   },function (err) {
      alert('error');
   }
);`
Other function (createHotspot, stopHotspot, isWifiOn, toggleWifi) work is fine.
In [wifiwizard](https://github.com/parsonsmatt/WifiWizard) both phones scan normal

**Comment by hypery2k** [comment]
the supported API Level 19 is 4.4+ 
Sorry to say but this plugin uses some APIs from API Level 19 and will not work completely with older versions
