### ISSUE TITLE
ionic support

### ISSUE THREAD

**Issue by joseangelmr** [hypery2k/cordova-hotspot-plugin#17]
Hello,
Would I like to know if this plugin is compatible with ionic framework?
Best regards

**Comment by hypery2k** [comment]
the plugin is working with Angular and Ionic but there is no injectable service or something like this

**Comment by joseangelmr** [comment]
Hi.
Any tutorial or snippet to use?. 
I am trying to use your plugin and I could not. You can help me please.
Best regards

**Comment by hypery2k** [comment]
you can look at the wiki sample: https://github.com/hypery2k/cordova-hotspot-plugin/wiki/Ionic-usage
