### ISSUE TITLE
WifiWizard

### ISSUE THREAD

**Issue by webmaster-imaginet** [hypery2k/cordova-hotspot-plugin#18]
Hi,

Maybe you want to merge WifiWizard into this plugin?

![image](https://cloud.githubusercontent.com/assets/4920443/13499321/63e2141c-e166-11e5-8108-dae2e1748477.png)

https://github.com/parsonsmatt/WifiWizard/issues/63

**Comment by hypery2k** [comment]
sorry but i don't will maintain the library
