### ISSUE TITLE
Extend cordova.plugins.hotspot.connectToHotspot

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/cordova-hotspot-plugin#19]
Have the option to connect to wifi with 4 parameters: ssid, password, authentication & encryption.
(This is for make sure that the wifi configuration is correct before pushing it to a wifi device for IOT)...

I saw in the android developer document & in your plugin that this is something that you can configure.
http://developer.android.com/reference/android/net/wifi/WifiConfiguration.AuthAlgorithm.html
http://developer.android.com/reference/android/net/wifi/WifiConfiguration.GroupCipher.html

should look like this
cordova.plugins.hotspot.connectToHotspot(ssid, password, auth, encryp, function () {

**Comment by webmaster-imaginet** [comment]
Actually I think that we can combined it with issue #12 so the name need to be:
**cordova.plugins.hotspot.connectToWifi**
or
**cordova.plugins.hotspot.connectToWifiAuthEncrypt**
