### ISSUE TITLE
plugin install

### ISSUE THREAD

**Issue by joseangelmr** [hypery2k/cordova-hotspot-plugin#23]
Hi
When I try to install the plugin in ionic tells me this error, is there some way to fix this?.

> Error: Failed to fetch plugin cordova-hotspot-plugin via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: Registry returned 404 for GET on https://registry.npmjs.org/cordova-hotspot-plugin

thanks you.

**Comment by hypery2k** [comment]
If you follow the README it's working: https://github.com/hypery2k/cordova-hotspot-plugin#installation
