### ISSUE TITLE
Can not remove created HotSpot

### ISSUE THREAD

**Issue by saherelm** [hypery2k/cordova-hotspot-plugin#24]
when we have a hotspot configuration, we can not create another or configure it or delete if after stop HotSpot ...

thanks
with the best regards.

**Comment by hypery2k** [comment]
can you please provide code snippets what exactly you're doing?

**Comment by saherelm** [comment]
hi, i want to do something like Zapy do ...  create a template HotSpot and Activate it ... then Delete it and restore Last Hot Spot Configuration ... 

i am trying to get last known hotspot configuration and store them ... then after done my works reconfigure it to last ... or null hotspot ... but i can't ...

with the best regards ...
Hadi Khazaee Asl

**Comment by hypery2k** [comment]
then please post your code. Maybe you're using the API not correctly. It's hard to help without any code snippet
