### ISSUE TITLE
Reference error

### ISSUE THREAD

**Issue by cajay01** [hypery2k/cordova-hotspot-plugin#25]
Whenever I build project it gives error  "ReferenceError: HotSpotPlugin is not defined" .I added plugin in cordova project then i made respective changes in config.xml but error is still their.How to resolve this?

**Comment by hypery2k** [comment]
refering to the [usage doc](https://github.com/hypery2k/cordova-hotspot-plugin/blob/master/PLUGIN_USAGE.MD#cordova.plugins.hotspot+createHotspot) the call you be something like this:

``` javascript:
cordova.plugins.hotspot.createHotspot(ssid, mode, password, successCB, errorCB)
```

**Comment by webmaster-imaginet** [comment]
Please check when you call the plugin.
you probably need to add
document.addEventListener("deviceready", function () { ...

**Comment by cajay01** [comment]
its solved
thank you
