### ISSUE TITLE
Support for android 6.x with the latest android cordova platform

### ISSUE THREAD

**Issue by webmaster-imaginet** [hypery2k/cordova-hotspot-plugin#30]
The plugin not working on android 6.x
I use it on android 6.x with cordova ver 4.1.1 but now it's look like it not working in this version anymore

![image](https://cloud.githubusercontent.com/assets/4920443/14646070/cc9875f4-0660-11e6-8529-37abcf227978.png)

**any chance to make it work on android 6.x?**

**Comment by hypery2k** [comment]
I don't haven any android 6 device to investigate this. Did you get any browser console errors or adb log entries?

**Comment by webmaster-imaginet** [comment]
I think that most of the methood callback are empty. so there are no errors.
Meaning that we get success callback but no data.

**for exmple:**

![image](https://cloud.githubusercontent.com/assets/4920443/14648748/79282c78-066c-11e6-9bb4-a7e6bb6d5611.png)

You can see that some methoods work, but scanWifi return empty array [ ]

**This is the ADB**
I don't know a better way to copy this (-:

![adb_logcat](https://cloud.githubusercontent.com/assets/4920443/14648763/86dade10-066c-11e6-8369-11df994fb7a6.png)

Hope it helps.

**Comment by hypery2k** [comment]
strange currently I don't get the issue and it's hard to debug via the emulator. Will try to get a Android 6 test device, but will take time

**Comment by webmaster-imaginet** [comment]
Do you know: [https://www.genymotion.com](url) or [http://www.andyroid.net](url) emulators?
Any how it's always best to check it on a real device (-:

**Comment by hypery2k** [comment]
Yes i know, but for genymotion you have to pay and testing wifi supposed to be not that easy anyway

**Comment by webmaster-imaginet** [comment]
Hi,
Any progress or estimate for that one? (-:

**Comment by hypery2k** [comment]
Currently don't have any android 6 device to debug this

**Comment by webmaster-imaginet** [comment]
Can we help you?

Is It makes sense to set a time that we will allows you to take control on a development machine that is connected to an Android device with version 6.x, and I will help you in the android operation for the tests?

We work on windows.
We have the latest "android studio"
Anything else that you may need? (-:

**Comment by hypery2k** [comment]
A remote session would be really difficult as I'm working at client side on weekdays and normally code this plugin in the train. 
Can you please try the latest master?

**Comment by webmaster-imaginet** [comment]
Hi,

I'm sorry for the delay, we had holiday. (-:
I install the master by using: cordova plugin add https://github.com/hypery2k/cordova-hotspot-plugin.git (that what you meant. yes?)

After that it still look the same. scan result is still return empty array.

![image](https://cloud.githubusercontent.com/assets/4920443/14940881/77eef0da-0f90-11e6-9774-7270bd21bdd6.png)

**Comment by hypery2k** [comment]
can you retry from the master?

**Comment by webmaster-imaginet** [comment]
Hi,

It's still the same... but it's look like that this is not only the wifi scan issue.
I get error also on "Manual Wifi Setup" & on "Barcode Scan" (https://github.com/hypery2k/cordova-barcodescanner-plugin.git)

**Info that may help:**
I use Ionic ver 1.2.4
![image](https://cloud.githubusercontent.com/assets/4920443/14977820/234c30b0-1120-11e6-9716-a2059124c7f4.png)

I don't change manualy the config.xml.
I install the app on the device using "ionic run".

# 

**this is "Auto scan"**

![image](https://cloud.githubusercontent.com/assets/4920443/14977725/4850adce-111f-11e6-8409-19825da1f3e8.png)

# 

**This is "Manual Wifi setup"**

![image](https://cloud.githubusercontent.com/assets/4920443/14977758/8e271a7c-111f-11e6-9bf7-fb8f33c99116.png)

# 

**This is for "Barcode Scan"**

![image](https://cloud.githubusercontent.com/assets/4920443/14978075/f5a261d2-1121-11e6-8714-de655ef42e95.png)

# 

I Shared with you a DropBox folder with:
the android-debug.apk (the app I use & show the console I show you here)
android.json + AndroidManifest.xml

**Comment by webmaster-imaginet** [comment]
BTW.
I use: chrome://inspect/#devices to see the app console. (-:

**Comment by hypery2k** [comment]
Hopefully the latest develop branch works. Try 

```
cordova plugin add cordova-plugin-hotspot@develop
```

**Comment by webmaster-imaginet** [comment]
Hi,

I Try cordova-plugin-hotspot@develop.

**I got this screen when the app go into "Auto scan"**

![image](https://cloud.githubusercontent.com/assets/4920443/14988253/c27589e4-115b-11e6-8692-0c9a2048b6fc.png)

**I pressed "Allow" but the app stop working**

![image](https://cloud.githubusercontent.com/assets/4920443/14988277/d6458b04-115b-11e6-9d73-2976d8639617.png)

**So I manually start the app again but still got the same results.**

![image](https://cloud.githubusercontent.com/assets/4920443/14988295/e56a836e-115b-11e6-8c3a-8c12763d404a.png)

**Comment by dudeofawesome** [comment]
Hey, I just wanted to chime in and say that I'm having this same issue on Android 6.0.1, but it works fine on a device with Android 4.4.1

I'm using the latest master release with Ionic2 and [ionic-native](https://github.com/driftyco/ionic-native)

**Comment by dudeofawesome** [comment]
When I tried to use the develop branch, I receive an error `Invalid action` whenever I call any of the plugin's methods.

It didn't create the permissions request popup that @webmaster-imaginet saw.

Here are the permissions that the app has requested
![screenshot_20160506-142636](https://cloud.githubusercontent.com/assets/1683595/15086610/d3b5ac4c-1396-11e6-8660-31bb721b1eeb.png)

**Comment by dudeofawesome** [comment]
Upon further investigation, it appears that you must request `ACCESS_FINE_LOCATION`, not `ACCESS_COARSE_LOCATION`

You can see a quick demo app I threw together for API > 23 that requests the proper permissions here [dudeofawesome/android-wifi-scan-test](https://github.com/dudeofawesome/android-wifi-scan-test)

I'm going to fork your repo and attempt to fix it myself right now.

**Comment by hypery2k** [comment]
you're right.

**Comment by dudeofawesome** [comment]
I've made the changes, but when I test it on my device, I'm still getting the `Invalid action` error. I'm pretty new to Cordova plugins, and ionic-native as well. From what I've been able to find, it seems that they're related to the plugin trying to call a function that doesn't exist. Is that right?

**Comment by hypery2k** [comment]
Seems that I should save the action before requesting permission. otherwise the action is later null ;)

Can you try the latest beta?:

```
cordova plugin add cordova-plugin-hotspot@1.2.0-beta1
```

**Comment by dudeofawesome** [comment]
I'm still getting the `Invalid action` error whenever I try to use a beta branch. The error occurs for all methods, not just `hotspot.wifiScan`

**Comment by hypery2k** [comment]
Mmmh strange, hopefully I get my hands on a android 6 device next week

**Comment by dudeofawesome** [comment]
In the meantime, I'll try to set up a plain Cordova app and test it to make sure it isn't a problem specific to Ionic2.

**Comment by dudeofawesome** [comment]
Ok, I used your example Ionic 1.x app with `1.2.0-beta1`, and I was able to complete a wifi scan.

I'm not sure what's up with my Ionic2 app, but it looks like it's not a problem with this project.

**Comment by webmaster-imaginet** [comment]
What version of cordova & android did you test it?
Can you add some print screen of the result of "ionic info"  + "cordova platform"

like this:

![image](https://cloud.githubusercontent.com/assets/4920443/15096612/9781a28e-1509-11e6-8fae-699acba2e8e4.png)

![image](https://cloud.githubusercontent.com/assets/4920443/15096614/a4205058-1509-11e6-9b20-beff1bf59309.png)

**Comment by dudeofawesome** [comment]
`$ ionic info`

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Framework Version: 1.2.4
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: Not installed
ios-sim version: 5.0.4
OS: Mac OS X El Capitan
Node Version: v5.11.0
Xcode version: Xcode 7.3 Build version 7D175
```

`$ cordova platform`

```
Installed platforms: android 5.1.1
```

But I actually ran it on a OnePlus One running 6.0.1

On a side note, you might seriously want to consider updating your node version at least to their LTS (4.4.4)

**Comment by webmaster-imaginet** [comment]
Thanks.

It's look like we have the same configuration from Ionic & Cordova version.
As you probably saw on this thread I got empty Array on Wi-Fi Scan.

I do not have this device under my hand at the moment, so I can't check the test app you mention.

did you try to use different cordova version?
It use to work for me on version 4.1.1 (ionic platform add android@4.1.1) but not anymore.

**Comment by dudeofawesome** [comment]
Have you tried installing `cordova-plugin-hotspot@1.2.0-beta1`?  That version has some necessary fixes to make scanning work.

**Comment by webmaster-imaginet** [comment]
Nope.
My Android ver 6.x is on his way to visit @hypery2k & I don't have a replacment for it at the moment.

**Comment by dudeofawesome** [comment]
So I just tried using the `1.2.0-beta1` with ionic-native on Ionic2, and manually gave it location permissions (by going in to settings and enabling it), which then made wifi scanning work.

##### There is also some other unexpected behavior.
- Calling `hotspot.toggleWifi` passes `Invalid action` to `errorCb`, but does successfully toggle WiFi
- `hotspot.getConnectionInfo`'s `IPAddress` has a preceding `/`

**Comment by webmaster-imaginet** [comment]
Hi Martin,

I'm sorry that I need to use the GitHub for this communication.

I sent you a few emails regarding the delivery of the parcel I sent you.
It is already in Germany but you need to take action to get it.

Please check the emails.

**Comment by hypery2k** [comment]
try to use the latest beta:

```
cordova plugin add ordova-plugin-hotspot@1.2.0-beta2

```

**Comment by webmaster-imaginet** [comment]
I don't have android 6.x in my hand.
Hopefully I will get one in a few days.

**Comment by webmaster-imaginet** [comment]
So,

**I test the latest version - 1.2.0-beta2 on android 6.0.1 device.** (same one that I sent you)
my results:
With the latest version of cordova android platform - 5.1.1 it still not working.
But I realized that it work again with cordova android platform ver 4.1.1

**Comment by dudeofawesome** [comment]
`1.2.0-beta2` is still acting the same way as `beta1` for me, where I have to manually give it location permissions via the Settings app.

I'll try to find some time to take a look at the plugin and fix it, but IDK when that'll happen.

**Comment by hypery2k** [comment]
I was able to debug on a device from @webmaster-imaginet and could solve the issue. Please verify with latest beta:
`
cordova plugin add ordova-plugin-hotspot@1.2.0-beta3
`

**Comment by webmaster-imaginet** [comment]
Hi,

I tested the 1.2.0-beta3 version with Cordova 5.1.1

![image](https://cloud.githubusercontent.com/assets/4920443/15393551/a4e361b2-1dd6-11e6-9606-c670ec9782f1.png)

![image](https://cloud.githubusercontent.com/assets/4920443/15393868/3c34d860-1dd8-11e6-92cd-8e83d4d43793.png)

![image](https://cloud.githubusercontent.com/assets/4920443/15393873/48a9678c-1dd8-11e6-9a3e-e00ec9534585.png)

## There are 2 main issues that I can find:

**Scan Wi-Fi still return empty array**

![image](https://cloud.githubusercontent.com/assets/4920443/15393586/ca6275fe-1dd6-11e6-987c-2282c3403b83.png)

**Connect to Wi-Fi returns error**

![image](https://cloud.githubusercontent.com/assets/4920443/15393612/ebe81a58-1dd6-11e6-85fb-bef40287711d.png)

## There is a small issue:

Configured Hotspot show "none" in the authentication field (android setting) even when configured with WPA2_PSK

I took the options from the documentation
![image](https://cloud.githubusercontent.com/assets/4920443/15393921/90fdc00a-1dd8-11e6-8e40-660c2d080212.png)

![image](https://cloud.githubusercontent.com/assets/4920443/15393889/66d032c2-1dd8-11e6-9d63-a26a33afca94.png)

I add the test app to our shared DropBox.
![image](https://cloud.githubusercontent.com/assets/4920443/15393848/21cd0cae-1dd8-11e6-9e8f-d73674206c36.png)
this is the file lshared link: https://www.dropbox.com/s/qdtgdr0g0cg6szy/android-debug.apk?dl=0

**Comment by hypery2k** [comment]
that's an error in the settings dialog in android. If you scan for that Wifi. You see that's encrypted

**Comment by dudeofawesome** [comment]
@hypery2k, Do you think that we could get a dialog to show explaining the request to modify system settings? I could see that being scary to users and it would be nice to have it explained before it is requested.

**Comment by webmaster-imaginet** [comment]
Hi,

I install the new plugin version 1.2.1 on the test app that I shared with this link:
https://www.dropbox.com/s/qdtgdr0g0cg6szy/android-debug.apk?dl=0

But I still got the same results as mention before:
1) Scan Wi-Fi still return empty array
2) Connect to Wi-Fi returns error

![image](https://cloud.githubusercontent.com/assets/4920443/15534249/a2bcb89a-2270-11e6-90f3-575f850f1ef5.png)

**Comment by webmaster-imaginet** [comment]
So I reduce cordova android version to 4.1.1 (instead of 5.1.1)

Now I got scan results, but still got error on connectToWifi methood.

![image](https://cloud.githubusercontent.com/assets/4920443/15534594/2a04d232-2272-11e6-941e-eb573f4803f0.png)

This is the app code for connectToWifi

![image](https://cloud.githubusercontent.com/assets/4920443/15534679/b8d8f39e-2272-11e6-9c56-7e361ea3c7fd.png)

**Comment by webmaster-imaginet** [comment]
I realized that I have a code error
"**function result() {**" instead "**function (result) {**"

I fixed it but it look that it still not working, there is no "result" in the callback fn 

![image](https://cloud.githubusercontent.com/assets/4920443/15535467/308b11f8-2276-11e6-848d-75a91aedc70b.png)

**Comment by hypery2k** [comment]
can you please open separate issues for the empty response calls, so I can track them?

**Comment by hypery2k** [comment]
@dudeofawesome Feel free to open a feature request issue.
I will close this one
