### ISSUE TITLE
Scan Wi-Fi return an empty array - Cordova android 5.1.1

### ISSUE THREAD

**Issue by webmaster-imaginet** [hypery2k/cordova-hotspot-plugin#33]
Hi,

I install the new plugin version 1.2.1 on the test app that I shared with this link:
https://www.dropbox.com/s/qdtgdr0g0cg6szy/android-debug.apk?dl=0

**Scan Wi-Fi return an empty array**

![image](https://cloud.githubusercontent.com/assets/4920443/15542648/4ae6d0ea-229a-11e6-9ca8-01cb932983fb.png)

**Comment by hypery2k** [comment]
The issue is that the function fails if wifi is turned off or if an hotspot is already active. I've add workaround for this and published a new release

**Comment by webmaster-imaginet** [comment]
Hi,

I install ver 1.2.2

![image](https://cloud.githubusercontent.com/assets/4920443/15568446/a22b4d46-2334-11e6-8afc-9110fd3fc375.png)

I tested it again with the sample app in 3 different conditions - all of them return an empty array
1) Wi-Fi off & Hotspot off
2) Wi-Fi on & Hotspot off
3) Wi-Fi off & Hotspot on

![image](https://cloud.githubusercontent.com/assets/4920443/15568437/920a2dc4-2334-11e6-9e89-2cb47e9873df.png)

**Comment by hypery2k** [comment]
Strange, Works for me

**Comment by webmaster-imaginet** [comment]
Are you using the latest cordova version 5.1.1 ?

**Comment by hypery2k** [comment]
yes, using 5.1.1 and just called scanWifi

**Comment by webmaster-imaginet** [comment]
Me too (-:

![image](https://cloud.githubusercontent.com/assets/4920443/15569180/88d86136-2338-11e6-8e57-2cec75d0ec4d.png)

Can you test it with the sample app? 
https://www.dropbox.com/s/qdtgdr0g0cg6szy/android-debug.apk?dl=0

**Comment by hypery2k** [comment]
getting scan results with your test app

**Comment by webmaster-imaginet** [comment]
very strange.
Have an idea how we get different results on the same device & android system with the same app ?

**Comment by hypery2k** [comment]
Not really. Can you try to complete remove the app and install it again? Then just call the scanWifi function

**Comment by webmaster-imaginet** [comment]
I test it again as you asked.
I had to confirm twice before scan occur

![image](https://cloud.githubusercontent.com/assets/4920443/15628232/a912fa92-2504-11e6-911d-73d654f62829.png)

![image](https://cloud.githubusercontent.com/assets/4920443/15628235/bcd1caea-2504-11e6-953e-2d136d8f8850.png)

Still got empty array

![image](https://cloud.githubusercontent.com/assets/4920443/15628245/04cf86ca-2505-11e6-9508-dc3d7731d70a.png)

@dudeofawesome can you please test the "Scan Wi-Fi" with the sample app on your 6.x device? 
https://www.dropbox.com/s/qdtgdr0g0cg6szy/android-debug.apk?dl=0
then just check the chrome console to see the results.

**Comment by hypery2k** [comment]
With cordova 5.1.1 on Android 5 and Android 6 all is working fine:
![developer_tools_-_file____android_asset_www_index_html](https://cloud.githubusercontent.com/assets/979121/15632074/5fb957a0-2587-11e6-9c8e-37869cc0c59f.png)

**Comment by NeoLSN** [comment]
I got the same issue on Samsung phone at Android 6.0.1.
Seems this issue only happens on Samsung phone.
@hypery2k Do you have any idea about this?
```
global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0 ios 4.5.2
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    ios-sim           : 6.1.2
    Node              : v9.0.0
    npm               : 5.5.1
    OS                : macOS High Sierra
    Xcode             : Xcode 9.1 Build version 9B55
```
Phone information
![image](https://user-images.githubusercontent.com/5782106/32600655-449ce1b8-c57b-11e7-8270-5db3fbe39a1c.png)
