### ISSUE TITLE
HotSpot authentication appears as "none" in android 4+

### ISSUE THREAD

**Issue by webmaster-imaginet** [hypery2k/cordova-hotspot-plugin#35]
When I'm using createHotspot OR configureHotspot methods, it appears wrong in the android setup.

**For exsmple:**

![image](https://cloud.githubusercontent.com/assets/4920443/15577971/4aab52cc-2367-11e6-8dcc-76fa5df075f8.png)

![image](https://cloud.githubusercontent.com/assets/4920443/15578024/7d149890-2367-11e6-86ca-d0c9ac980dde.png)

![image](https://cloud.githubusercontent.com/assets/4920443/15578036/882ea018-2367-11e6-94de-b3cb43dd27a3.png)

And when choose manualy WPA2 PSK the password is empty

![image](https://cloud.githubusercontent.com/assets/4920443/15578141/003a26b8-2368-11e6-8a4b-08f9e2956def.png)

**So I check how it works with another app:**
https://play.google.com/store/apps/details?id=com.stt.mobilehotspot

And it display the Hotspot configuration corectly - So I guess it's something to do with the plugin

![image](https://cloud.githubusercontent.com/assets/4920443/15578169/1c433f2a-2368-11e6-9b1a-fdde6766783e.png)

![image](https://cloud.githubusercontent.com/assets/4920443/15578200/37dbc5fe-2368-11e6-8c72-e6d371f13900.png)

![image](https://cloud.githubusercontent.com/assets/4920443/15578212/4715270e-2368-11e6-9c89-275582a94ef0.png)

**Comment by hypery2k** [comment]
if you do a wifi scan it's showing that the security settings are picked up correctly

**Comment by hypery2k** [comment]
keep in mind that WPA2_PSK or no security is the only option in Android 6. So if running on Android 6 the user can only select to security options:
- none
- WPA/WPA2

**Comment by webmaster-imaginet** [comment]
Hi,

the screen shot I add when I opened this issue are from LG Nexus 4 running android 5.1.1.
I check the new plugin version 1.2.3 but got the same "none".

On the version 6.0.1 it's work now fine.

**Comment by hypery2k** [comment]
I'll check it later with an older device

**Comment by hypery2k** [comment]
Fixed in version 1.2.4
