### ISSUE TITLE
Connection to software access point

### ISSUE THREAD

**Issue by cajay01** [hypery2k/cordova-hotspot-plugin#36]
connection to wifi through this plugin works fine but connection to Soft AP is not happening.why?

**Comment by hypery2k** [comment]
did you have any more information about your setup? Which Cordova version, Android version, device, wifi settings? Without any more information it's hard to say which might be the issue. Logs (adb logs) would be also very helpful

**Comment by cajay01** [comment]
cordova version 6.0.0
node version 0.10.40
device is galxy S5 having lolipop
and when I call 
cordova.plugins.hotspot.connectToWifi($scope.nWName, $scope.data.wifi, 
          function(){
            console.log("Connection to wifi successful");
            $ionicLoading.hide();
            sendinfo();
        }, function(){
          console.log("Connection to wifi failed");

```
    });
};
```

it gives me connection to wifi failed

**Comment by cajay01** [comment]
hi ,also using this plugin we can scan the android AP devices but not able to connect them

**Comment by webmaster-imaginet** [comment]
check your "SSID" & "Password"

```
cordova.plugins.hotspot.connectToWifi(ssid, password, 
       function (result) {...
```

one of your **$scope** has .data & the other not.
$scope.nWName
$scope.data.wifi

Also you can test some of the plugin methoods with this ionic sample app (inculding connectToWifi)
https://www.dropbox.com/s/vco2a5o9w8z276j/android-debug.apk?dl=0
just look at the console with chrome://inspect/#devices

**Comment by cajay01** [comment]
Both fiels have data $scope.nWName contains SSID of nw and $scope.data.wifi contains password for that SSID

**Comment by webmaster-imaginet** [comment]
i meant that maybe you need **$scope.data.nWName** instead $scope.nWName

**Comment by cajay01** [comment]
your app is able to connect with soft ap

**Comment by cajay01** [comment]
did you make any changes in plugin?
Plz let me know

**Comment by cajay01** [comment]
Actually I keep $scope.nWName separate from $scope.data{} so I have SSID as $scope.nWName and Password as $scope.data.wifi

**Comment by webmaster-imaginet** [comment]
I didn't change anything in the plugin.
In what platform you are developing your app?
Ionic / Phongap?

**Comment by hypery2k** [comment]
can you connect manually via chrome debug and check if it's working without any angular stuff around?

**Comment by cajay01** [comment]
I am working on ionic platform
manually it connects

**Comment by cajay01** [comment]
@webmaster-imaginet
can you share your code with me so that I can check where I am doing wrong?

**Comment by hypery2k** [comment]
You can install the APK and debug it. Then you see the source code

**Comment by hypery2k** [comment]
Closing due to no feedback
