### ISSUE TITLE
getting error while installing the package 

### ISSUE THREAD

**Issue by cajay01** [hypery2k/cordova-hotspot-plugin#37]
Getting error while fetching compat plugin

Installing "cordova-plugin-hotspot" for android
Fetching plugin "cordova-plugin-compat" via npm
Failed to install 'cordova-plugin-hotspot':Failed to fetch plugin cordova-plugin
-compat via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND
    at registry.fetch.fail.then.pinfo (C:\Users\inachavan\AppData\Roaming\npm\no
de_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:146:33)
    at _rejected (C:\Users\inachavan\AppData\Roaming\npm\node_modules\cordova\no
de_modules\q\q.js:797:24)
    at C:\Users\inachavan\AppData\Roaming\npm\node_modules\cordova\node_modules\
q\q.js:823:30
    at Promise.when (C:\Users\inachavan\AppData\Roaming\npm\node_modules\cordova
\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\inachavan\AppData\Roaming\npm\n
ode_modules\cordova\node_modules\q\q.js:741:41)
    at C:\Users\inachavan\AppData\Roaming\npm\node_modules\cordova\node_modules\
q\q.js:557:44
    at flush (C:\Users\inachavan\AppData\Roaming\npm\node_modules\cordova\node_m
odules\q\q.js:108:17)
    at process._tickCallback (node.js:448:13)
Error: Failed to fetch plugin cordova-plugin-compat via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

**Comment by hypery2k** [comment]
seems like an error at you client setup: https://github.com/npm/npm/issues/3354
