### ISSUE TITLE
cordova is not defined in controller.js 

### ISSUE THREAD

**Issue by ramansathiyanarayanan** [hypery2k/cordova-hotspot-plugin#38]
Hi there,
    I took the hotspot-app and tried using into an android app but I'm getting following errors when I'm loading it a browser using **ionic serve** command. The first error the browser console says is **module starter is not defined or mispelled**. Then I added it in the **body** tag using **ng-app** directive. Then I'm getting the error **"cordova is not defined in controller.js"** and if I remove the **manual  bootstrapping** method then I don't get any error but the page is just blank. Please give me a suggestion to how to fix it.I'm using ionic CLI v1.7.16 and cordova CLI v6.2.0

**Comment by hypery2k** [comment]
Getting the same error. 

Truth to told, I'm not using this example anymore and did not have much time for working on this.

Sorry to tell.

**Comment by ramansathiyanarayanan** [comment]
K, if you have time for a little, I will tell u what I have done so far. So, I'm building a wifi App by myself using **cordova-plugin-wifiWizard**. In this app I can even crack the password protected networks by validating it from the network. But I'm unable to configure my wifi Application for an enterprise network where you will have some more validations like **identity, username and password and so on**. So do you have any idea on how can I approach for an **enterprise** wifi networks.

**Comment by yoffe** [comment]
Hi,

you are not supposed to work with cordova plugins in the browser.
Ionic serve is for testing the app (not the native parts = cordova) on the browser.
cordova plugins need to run on a real device / emulator.

hope it helps.

**Comment by ramansathiyanarayanan** [comment]
Yes, you are right. Thanks for that, but we will be able to see the errors we make in the program(javascript) by using the browser's console. And do you have got any idea about the above question I asked in the command about the enterprise network.

**Comment by hypery2k** [comment]
deploy the app on a device and work with the debugger.

**Comment by ramansathiyanarayanan** [comment]
K, will u guys please tell me some ideas or steps on how to build a wifi app which can even get the list of enterprise network with their registration and then authentication
