### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by makarandcodes** [hypery2k/cordova-hotspot-plugin#40]
I am developing android app in Ionic 2. 

Getting this error that the "Property 'hotspot' does not exist on type 'CordovaPlugins'."

![capture](https://cloud.githubusercontent.com/assets/19259373/17250826/bab10dee-55c3-11e6-9be3-89d79661fa5c.PNG)

My Ionic App is created from the template 'Blank App', and above code is of the Main Page Typescript File which is main.ts

I am tired of searching over and over for it, unable to find answer. Maybe someone here can help me out with this.

I am kinda newbie here so a detailed answer would be really helpful. Thank You.

**Comment by hypery2k** [comment]
have to provide type definitions. Try to add them the next week

**Comment by strappsdev** [comment]
try adding 

declare var cordova : any;

to main.ts

**Comment by hypery2k** [comment]
the plugin is discontinued, so I will not maintain this repo anymore
