### ISSUE TITLE
Hotspot issue particularly for Android 5.1.1 security not setting

### ISSUE THREAD

**Issue by shraddha1112** [hypery2k/cordova-hotspot-plugin#44]
Hello,
We are using your plugin and for Android 6.0+ it is working fine. But for 5.1.1 we are able to turn on hotspot but cannot set the security it is automatically getting configured to OPEN.
                    cordova.plugins.hotspot.createHotspot('myHomeHotspot', 'WPA2PSK', password, successHotSpot, errorHotSpot);

Please help.

Regards,
Shraddha

**Comment by hypery2k** [comment]
I've tested in with Android 5 and 6 and was working for me. Did you have any adb logs from Android 5?

**Comment by shraddha1112** [comment]
Its coming particularly for 5.1.1 
[Notsettingpasskey.txt](https://github.com/hypery2k/cordova-hotspot-plugin/files/424407/Notsettingpasskey.txt)

08-18 11:39:42.698: I/System.out(31594): Cancel clicked
After this log hotspot call is given.

**Comment by hypery2k** [comment]
as i can see it's setting wpa:

```
08-18 11:39:43.299: D/(301): CMD INPUT  [set wpa_passphrase=0a0b0f62170ecc5bcf721b6ff170b8b560101b5d56b00a26abec217e0bb4aa1][255]
08-18 11:39:43.299: E/(301): Cmd: wpa_passphrase Argument :0a0b0f62170ecc5bcf721b6ff170b8b560101b5d56b00a26abec217e0bb4aa1 
08-18 11:39:43.299: D/(301): cmd=wpa_passphrase, Val:0a0b0f62170ecc5bcf721b6ff170b8b560101b5d56b00a26abec217e0bb4aa1, INI:0 
08-18 11:39:43.300: D/(301): Updated:wpa_passphrase=0a0b0f62170ecc5bcf721b6ff170b8b560101b5d56b00a26abec217e0bb4aa1
```

Did you checked if the provided wifi is really open? Just scan for wifi with other devices. Sometimes there are issues with the UI refresh

**Comment by shraddha1112** [comment]
No it is setting with OPEN security. WPA is not getting configured.

**Comment by hypery2k** [comment]
I cannot find any LOG_CAT entry in your log file with TAG "HotSpotPlugin" or "WifiHotSpots" Can you try to install a debug APK to your device with the latest develop branch installed and post the output?

**Comment by hypery2k** [comment]
closed due to no response
