### ISSUE TITLE
Devices can't connect unless I reset AP

### ISSUE THREAD

**Issue by bknill** [hypery2k/cordova-hotspot-plugin#47]
Hi, great plugin. 

I've got it creating the hotspot OK, however the cameras I'm using couldn't connect to it. If I change something in the AP settings in Android, i.e. change the password and then change it back, they connect fine but then I can't scan the hotspot for devices - which is the main feature I wanted to use. Scanning comes back with an empty array.

This is on Android 4.4.2

Is there anything I could be missing?

**Comment by hypery2k** [comment]
depends on what you're setup is. please tell more about your setup:

Tell about your environment:
- operating system and version
- cordova version
- Android version
- java version
- code you're using
