### ISSUE TITLE
Same error as issue #14 on toggleWifi

### ISSUE THREAD

**Issue by LuisMAlmeida** [hypery2k/cordova-hotspot-plugin#48]
Hi there,

I still got the same error as issue #14 
```
cordova.plugins.hotspot.toggleWifi(function(start){
                                    alert("Sucess!");
                                    isWifiOn=start;
                                    }, 
                                   function(start){
                                    alert(start);
                                    isWifiOn=start;
                                    })
```
Executing this I get and alert saying "Invalid Action" and the Wifi is turned-on, if i execute it again while the wifi is On, it gets turned off and the same alert with the same error pops up.

Can you look into it again please?

Thank you very much

**Comment by hypery2k** [comment]
before opening, please tell more about your setup:
- Tell about your environment:
  - operating system and version
  - cordova version
  - Android version
  - java version

**Comment by LuisMAlmeida** [comment]
Sure thing:
- Windows 10
- Cordova 5.1.1
- Android 4.4.2 and Android  6.0

I code in Outsystems, and I've integrated it with several Cordova Plugins.
This issue happens on both android versions, the function works, it toggles wifi On/Off but it always executes the ErrorCB

**Comment by jamespatrickwhite** [comment]
It looks like the toggleWifi if block in HotSpotPlugin.java is missing the `return true;` line that acknowledges a successful plugin call, and also needs updated return values for on/off reporting.
My modified block looks like this:

``` javascript
        if ("toggleWifi".equals(action)) {
            threadhelper(new HotspotFunction() {
                @Override
                public void run(JSONArray args, CallbackContext callback) throws Exception {
                    if (toggleWifi()) {
                        callback.success(1);
                    } else {
                        callback.success(0);
                    }
                }
            }, rawArgs, callback);
            return true;
        }
```

**Comment by hypery2k** [comment]
@jamespatrickwhite: Thanks for the hint. Feel free to send a PR next time ;)

**Comment by hypery2k** [comment]
fixed in latest release
