### ISSUE TITLE
startWifiPeriodicallyScan Can you give me an implementation example?

### ISSUE THREAD

**Issue by LuisMAlmeida** [hypery2k/cordova-hotspot-plugin#49]
Hi there,

I'm implementing almost all this functions in my APP and so far so good although i'm having troubles with startWifiPeriodicallyScan, probably i'm implementing it wrong.

I have this implementation

```
`cordova.plugins.hotspot.startWifiPeriodicallyScan(30000,Number.MAX_SAFE_INTEGER, 
                                                              cordova.plugins.hotspot.scanWifi(function(jsonwifi){
                                                                     jsonwifi.forEach(function (element){
                                                                    console.log(JSON.stringify(element));});}, 
                                                               function(){})
                                                       , function(){console.log('ERROR');});`

```
What is happening is that only  the first iteration is working, when I start startWifiPeriodicallyScan it runs once and then stops, I've tried with a duration of 120000 and the behavior is the same.

Am I not supposed to call the scanWifi in the sucessCB?
What am I doing wrong?
For a workarround I can just use the JS setInterval but I would like to use this one.

Thank you very much,
Luís Almeida

**Comment by hypery2k** [comment]
sorry, but having currently no time to help you on this
