### ISSUE TITLE
EAP/TTLS support

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/cordova-hotspot-plugin#53]
https://github.com/nagad814/wifiEnterprise/blob/master/src/android/com/ants/plugin/wifienterprise/WifiEnterprise.java#L452

**Comment by hypery2k** [comment]
a nightly build is available via *cordova-plugin-hotspot@1.2.7-11*

**Comment by hypery2k** [comment]
@nagad814 did you had to chance to test it?

**Comment by nagad814** [comment]
Hi , Martin.

I was unwell and did not work at all. I have recovered and back to work
today. will reply back quicker. Sorry for leaving you in the dark.
