### ISSUE TITLE
Create Hotspot error = write settings: false

### ISSUE THREAD

**Issue by jfont555** [hypery2k/cordova-hotspot-plugin#55]
Hi, i'm using your plugin through ionic2 ionic-native. And i'm getting this error when creating a hotspot: 

write-settings: false.

my config:

Cordova CLI: 6.3.1 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
Node Version: v5.12.0

Manifest permissions: 

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

Thanks in advance ;)

**Comment by tyleha** [comment]
I too am getting this problem on Android 6.0.1 using Cordova 5. 

```
cordova.plugins.hotspot.connectToWifi('ssid', 'pw', function(res) {
  console.log(res)
}, function(err) {
  console.log(err)
});
```

This throws an error with the string `write settings: false`

**Comment by hypery2k** [comment]
which plugin version you're using?

**Comment by tyleha** [comment]
1.2.7, the latest I believe

**Comment by alvaroslm** [comment]
I'm getting this issue too I think. I'll look into it.  @hypery2k If you want me to test anything on an Android 6 device give me the code and I'll get back to you asap. Btw, I'm using the latest Ionic 2 and plugin versions

> `02-07 20:09:55.385: D/HotSpotPlugin(4847): Can Write Settings: false`
`02-07 20:09:55.385: W/CordovaPlugin(4847): Attempted to send a second callback for ID: HotSpotPlugin1638736277`
`02-07 20:09:55.385: W/CordovaPlugin(4847): Result was: "Invalid action"`
`02-07 20:09:55.411: D/HotSpotPlugin(4847): Can Write Settings: false`
`02-07 20:09:55.411: W/CordovaPlugin(4847): Attempted to send a second callback for ID: HotSpotPlugin1638736278`
`02-07 20:09:55.411: W/CordovaPlugin(4847): Result was: "Invalid action"`
`02-07 20:09:55.416: D/SystemWebChromeClient(4847): file:///android_asset/www/build/main.js: Line 15 : VWIZWIFI- toggle failed: write settings: false`
`02-07 20:09:55.416: I/chromium(4847): [INFO:CONSOLE(15)] "VWIZWIFI- toggle failed: write settings: false", source: file:///android_asset/www/build/main.js (15)`

**Comment by alvaroslm** [comment]
Ok, now it works for me. I commented out the write settings part and the permissions check (why are you asking for FINE_LOCATION -and just that- anyway?). And why'd you want to be able to write to system settings in all use cases?
I need none of that and it works fine on Android 6 (I'm only scanning, connecting and disconnecting from wifi networks). I'm targeting API 23 and I have my permissions set on the manifest.

**Comment by IrineuSilva** [comment]
Changed the target to API 22 and worked. Seens that  API level 23 consider WRITE_SETTINGS to be special permission that require a intent request, not even cordova.plugins.permissions. requestpermission is enought. https://developer.android.com/reference/android/Manifest.permission.html#WRITE_SETTINGS

**Comment by IrineuSilva** [comment]
CahngedAPI level to 22 and now it is working. Seens to be related to the fact WRITE_SETTINGS is now a special permission. https://developer.android.com/reference/android/Manifest.permission.html#WRITE_SETTINGS

**Comment by hypery2k** [comment]
Published version 1.2.8

**Comment by jfont555** [comment]
this issue is still present in version 1.2.8. I'm using the plugin to create, start & modify a hotspot.

**Comment by ansario** [comment]
@alvaroslm what did you comment out?

**Comment by danfleser** [comment]
@hypery2k did you managed to solve the error ?
I am at 1.2.8 and still get this error: write settings: false at createHotspot("test", "WPA_PSK", "pass") function :(

if it helps: I am using Android 7.0
and when I run the app: ionic cordova run android
in the project/platforms/android/AndroidManifest.xml this permission
<uses-permission android:name="android.permission.WRITE_SETTINGS" />
DOES NOT APPEAR 👎 

can you do sth?

I tried to put it manually nut does not work. I still get: write settings: false, but I saw u have i your plugin, can you recheck and see why it does not append to main AndroidManifest?
btw: all your other permissions 
appear in main AndroidManifest.xml

**Comment by hypery2k** [comment]
sorry to say but I discontinued this plugin. So I'm not maintaining it anymore.

**Comment by danfleser** [comment]
@hypery2k ok

**Comment by ansario** [comment]
@danfleser  if you are targeting SDK 23 or above, make sure you have `<uses-permission android:name="android.permission.WRITE_SETTINGS">` in your manifest and then you'll need to request permission from the user manually like this:

```
cordova.plugins.hotspot.getWriteSettings(result => {
           console.log(result);
           if (!result)
           {
               cordova.plugins.hotspot.requestWriteSettings(response => {
                   console.log(response);
               });
           }
       });
```

**Comment by danfleser** [comment]
@ansario Thanks man!!!

**Comment by jonathanjames86** [comment]
@ansario Could you explain where you are getting the .getWriteSettings()? I can't find it as a property of hotspot... Am I missing something obvious? Thanks

**Comment by adamlacombe** [comment]
@jonathanjames86 it doesn't seem to be available in the Ionic Native plugin.

You can access the cordova plugin directly though. Place `declare var cordova;` above the @Component decorator to make Typescript happy
