### ISSUE TITLE
issue, with "Android write settings", Shows always false. No permission is checked.

### ISSUE THREAD

**Issue by dahomost** [hypery2k/cordova-hotspot-plugin#56]
Hello,

I'm getting same issue as jfont555 "Commented on Dec 6 2016", I wish the plugin could be tested & fixed.

After adding HotSpot Plugin and build the App, No permission is checked or asked at the installation, it shows "write settings = false".  So I have to do it manually in the "Application Manager" / Change System Settings, and grand "write Settings".

I'm using:
- Cordova CLI: 6.2.0
- Android 6.0
- API level: 23   Revision: 3
- Ionic Framework Version: 2.0.0-beta.9
- Ionic CLI Version: 2.0.0-beta.25
- Ionic App Lib Version: 2.0.0-beta.15
- Gulp version:  CLI version 3.9.1
- Gulp local:   Local version 3.9.1 
- Node Version: v4.4.4
- and these plugins:
                     cordova plugin add cordova-plugin-whitelist
                     cordova plugin add cordova-plugin-network-information
                     cordova plugin add cordova-sqlite-storage
                     ionic plugin add cordova-plugin-hotspot

it was working fine few month before, but after re-installing the hotspot plugin version " 1.2.7 " again, The App doesn't ask for the Permission anymore at the installation.

**And this is a part of my AndroidManifest.xml**

    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="23" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WRITE_SETTINGS" />

**This is the warning that I'm getting during the build**:

:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\git\minestar-technician-mobile-app\platforms\android\src\de\martinreinhardt\cordova\plugins\hotspot\HotSpotPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Thank you

**Comment by hypery2k** [comment]
which version of cordova, Android, and the plugin are you using?

**Comment by dahomost** [comment]
Hello

I'm using

   -
*Cordova 6.2.0 *
   -
*Android 6.0 API 23 *
   - *and the plugins:*


   - cordova plugin add cordova-plugin-whitelist
      - cordova plugin add cordova-plugin-network-information
      - cordova plugin add cordova-sqlite-storage
      - ionic plugin *add cordova-plugin-hotspot*

it was working fine few month before, but after re-installing the hotspot
plugin version " *1.2.7* " again, The App *doesn't ask for the
Permission* anymore
at the installation.

*Thank you for your help.*
*Med *

**Comment by yoffe** [comment]
The latest Cordova for Android is 6.1.1 (or you meant 6.2.0 for cordova cli)

**Comment by dahomost** [comment]
Hi,

Cordova CLI: 6.2.0

Android 6.0
API level: 23   Revision: 3

Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15

Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1

Node Version: v4.4.4

Thank you

**Comment by yoffe** [comment]
So what Cordova version are you using?

look at the your **platforms.json** file in the **platforms** folder (in your ionic project)
it will look somthing like that
`{
    "android": "6.1.1"
}`

BTW, Ionic has Version: **2.0.0-rc.4** so why you are still using the beta?

**Comment by dahomost** [comment]
Hi,

Actually my platforms.json, shows

{
    "android": "5.1.1"
}

so if I upgrade to *2.0.0-rc.4* ,
the permissions to changes settings will be fixed

Thank you

**Comment by yoffe** [comment]
Nothing to do with ionic version here.
I only mention it because it's old version.
and while we are talking the ionic team release 2.0.0-rc.5

Regarding your error, please wait for @hypery2k

**Comment by dahomost** [comment]
**Permission Issue fixed** on my Tablet running **Adnroid 6.0**, 
I removed my Cordova 6.2 , and I installed **Cordova 5.4** 
**npm install -g cordova@5.4**
I build the App targeting : 
- Android-4.4.2 - API 19 ,   
- Android-4.4W.2 - API 20,    
- Android-5.0.1  API-21  
- Android-5.1.1  API-22  
- Android-6.0 API-23

**Comment by hypery2k** [comment]
@dahomost Which cordova-android version you're using?

**Comment by hypery2k** [comment]
Published version 1.2.8

**Comment by dahomost** [comment]
Hi Martin,

I would like to takeover the "Cordova Hotspot" project, I already fixed
some issue on our Mobile App
I work with a team in CATERPILLAR Peoria - ILLINOIS  and remotely , and I'm
willing to collaborate with my team to update the plugin and reply to all
posted issues.

Thank you

Med Daho
Caterpillar, Peoria IL
Luminous Tec
+1 571-581-0091

On Fri, Feb 24, 2017 at 12:52 AM, Martin Reinhardt <notifications@github.com
