### ISSUE TITLE
.connectToWifi  issue

### ISSUE THREAD

**Issue by dahomost** [hypery2k/cordova-hotspot-plugin#57]
Hi,
I'm testing my App (Ionic / Angular) on Galaxy Tab S2.
Hotspot.connectToWifi(SSID, Password) cannot connect to the selected SSID, because of the **Settings/WIFI,** 

The **Settings/Wifi** try to connect in parallel using SSID with saved passord, witch bother my App to connect.

To fix this, I have to delete all the saved password in the Settings/Wifi, and then the "Hotspot.connectToWifi" works fine, is ther anyway to avdoid this manual solution,

Does .getWriteSettings works, I cannot see it among the Hotspot methods.

Thank you.

**Comment by Ashish1611** [comment]
Hotspot.connectToWifi("SSID","Password").then(()=>{
             console.log('Connected to User');
           // display alert here
      });

because for  me it works successfully

**Comment by dahomost** [comment]
what android version, you have on your Mobile Device

**Comment by Ashish1611** [comment]
4.1.1 ice cream sandwhich

**Comment by dahomost** [comment]
When I try  to connect to a selected SSID, the connection fails most of the time, probably because of the concurrence of the **wifi of the device settings**,  to fix this issue, I have to go to the Tablet settings and ignore all saved connection and passwords, and then try connection using the hotspot plugin, it works fine.

is the a way to block the device settings automatic scan to handle the wifi connection exclusively.

Thank you

**Comment by hypery2k** [comment]
when submitting bugs would be really helpful to tell more about your's setup as mentioned during opening an [issue](https://github.com/hypery2k/cordova-hotspot-plugin/blob/master/CONTRIBUTING.MD).

**Comment by dahomost** [comment]
Hello,

I sent this issue a long time ago, but I didn't get a feedback,
Most of the time,  Hotspot.connectToWifi(SSID, Password) cannot connect to the selected SSID, because of the Settings/WIFI.  The problem is that The **# Settings/Wifi** uses **# saved passwords** to connect in parallel as well, 

so to fix this, I removed all passwords from the Settings/Wifi, and then my Hotspot.connectToWifi works fine, I can connect all the time.

I did another experiment, I restored all passwords in Setting/Wifi, and tried another plugin WifiWizard, this plugin is faster and connect to any SSID without problem. but it's not optimized for Ionic / Angular 2. and I cannot used.

I think, if Hotspot plugin connection speed could be increased, just like WifiWizard plugin, the connection issue could be fixed, without deleting the Passwords in the Tablet/Settings/Wifi.

conclusion:
The Setting/Wifi in the Tablet scans & connects automatically to SSID using saved passwords. this cause a big issue for hotspot plugin to connect in parallel, I guess Hotspot plugin is slower than the Table/Settings/Wifi.  If I remove these passwords, then the hotspot plugin works fine.

is there a way to block the Device Automatic SCAN & Connection, or increase the hotspot connection speed, just like WifiWizard.  Thank you

I' using : 
- Cordova CLI: 5.4.1
- Ionic CLI Version: 2.2.1
- Ionic App Lib Version: 2.2.0
- OS: Windows 10
- Node Version: v6.9.5

Android platform:
   - Android 4.4.2
    - API level: 19
 
Regards

**Comment by hypery2k** [comment]
to be honest, I currently don't have much time as I'm having a full-time job.

So any PR is welcome. The project is free and contribution is welcome

**Comment by gregor-srdic** [comment]
I also encountered this problem. If Wi-Fi is already saved in Android settings, connectToWifi will not work. After you choose to "forget" the network in Android settings, it works. Tested with Android 6.0.

**Comment by hypery2k** [comment]
sorry to say, but I will discontinue this plugin as I don't have any more time for this

**Comment by rjw** [comment]
I've found a simple workaround for this is to just make a:

removeWifiNetwork(ssid)

call, and once the promise resolves or rejects, continue with the connection attempt. This has worked fine for me so far.

Sorry to hear this plugin will be discontinued, it's a shame as it's really useful and it's looking pretty essential for the project I'm working on!

**Comment by sudhan-ionic** [comment]
i try removeWifiNetwork(ssid) but not connected @rjw

**Comment by NeoLSN** [comment]
Can anyone help me test on different device.
Currently, I only tested on Galaxy S5 with Android 6.0.1. And it works well.
https://github.com/NeoLSN/cordova-hotspot-plugin
