### ISSUE TITLE
get current Hotspot SSID

### ISSUE THREAD

**Issue by webmaster-imaginet** [hypery2k/cordova-hotspot-plugin#6]
add a method to get the current Hotspot SSID before use "configureHotspot" or "createHotspot" in case you want to save it for restoring back

**Comment by hypery2k** [comment]
https://github.com/hypery2k/cordova-hotspot-plugin#get-connection-configuration is not working for this?

**Comment by webmaster-imaginet** [comment]
The "cordova.plugins.hotspot.getConnectionInfo" work on wifi but not on hotspot. 
You can see the results from three options that I checked:

![getconnectioninfo](https://cloud.githubusercontent.com/assets/4920443/12536999/36f63aae-c2bd-11e5-800f-b03983bec14a.jpg)

**Comment by hypery2k** [comment]
I think it's not possible at it seems the Android API doesn't show this info in HotSpot mode

**Comment by webmaster-imaginet** [comment]
O.K. I understand (-:
