### ISSUE TITLE
isWifiOn always returns false

### ISSUE THREAD

**Issue by vicatcu** [hypery2k/cordova-hotspot-plugin#65]
I'm back to trying to use this plugin with the ionic-native wrapper in ionic2... 

```javascript
this.hotspot.isWifiOn().then((connected) => {
  console.log(`isWifiOn? ${connected}`);
}).catch((e) => {
  console.log(`isWifiOn error`, e);
});
```
... prints nothing but `isWifiOn? false` in the Chrome remote debug console connected to code running on an Android phone; regardless of whether I have Wi-Fi enabled or disabled in Android settings.

```
ionic info
  Cordova CLI: 6.5.0 
  Ionic Framework Version: 2.3.0
  Ionic CLI Version: 2.2.2
  Ionic App Lib Version: 2.2.1
  Ionic App Scripts Version: 1.1.4
  OS: Linux 4.6
  Node Version: v6.10.0

ionic-native@2.9.0
@ionic-native/hotspot@3.4.2
cordova-plugin-hotspot@1.2.8
```

**Comment by hypery2k** [comment]
can you try with 1.2.9?

**Comment by hypery2k** [comment]
the plugin is discontinued, so I will not maintain this repo anymore
