### ISSUE TITLE
Do you support event monitoring when device connections are made?

### ISSUE THREAD

**Issue by baiej214** [hypery2k/cordova-hotspot-plugin#66]
Hi @hypery2k , When a hot spot is attached to a mobile phone, can hot spots prompt for support for event monitoring, such as "onConnect" or something like that? Thanks.

**Comment by hypery2k** [comment]
as the plugin is discontinued, no

**Comment by baiej214** [comment]
@hypery2k Well, I just saw what you said before. One more question is whether any of the same Cordova plug-ins can be used? Because my APP relies very heavily on your plug-in. Thank you.

**Comment by hypery2k** [comment]
currently i don't have any time, because I did it in my spare time and just takes to much time of maintaining ....
Didn't know if there is any other plugin around ...

**Comment by baiej214** [comment]
@hypery2k Well, since you say so, but thank you, are of great help to you and your plugin for my APP, hope this plugin can continue, I will continue to pay attention to this project, thank you again.

**Comment by hypery2k** [comment]
if somebody takes over sure, otherwise the plugin will stay-as-is
