### ISSUE TITLE
Data communication Usage

### ISSUE THREAD

**Issue by Dipayon3D** [hypery2k/cordova-hotspot-plugin#73]
Can I use this plugin for data communication ??

**Comment by hypery2k** [comment]
did't get what you mean with that. A hotspot is used to exchange data ;)

**Comment by Dipayon3D** [comment]
Exactly :) How can I exchange data using this plugin ? I didn't find and API for that . . . If it's already there, please point me at the right direction . . .

**Comment by hypery2k** [comment]
So what’s your use case? You want to send data between the devices connected to the devices?

**Comment by Dipayon3D** [comment]
Yes . . . i want to make a Multiplayer game, like Doodle Army 2: Mini Militia

**Comment by hypery2k** [comment]
Sorry but you have to do this on your own with the help of HTTP ;)

As this plugin is not maintained anymore I will no add such features

**Comment by Dipayon3D** [comment]
I understand . . . So, should I use another plugin for server socket creation and connection ??

**Comment by hypery2k** [comment]
Yes

**Comment by Dipayon3D** [comment]
Ok . . . Thanks.
