### ISSUE TITLE
get mac address for Ethernet adapter  not for wifi adapter 

### ISSUE THREAD

**Issue by NayHaPal** [hypery2k/cordova-hotspot-plugin#75]
hello all,
Can i get mac address for Ethernet adapter  of device not for WiFi adapter its has different mac address 
I want to get that for TV device build on android OS.
see the mac address of my device its different mac address.

![untitled-1](https://user-images.githubusercontent.com/7863464/31339285-00ddb32c-ad0b-11e7-9abe-b8465dd4a2b9.png)

Thanks

**Comment by NayHaPal** [comment]
please i make a new function to get the mac address for the Ethernet and create new api to arrive to this function 

Please this function get the Ethernet `eth0` of the device 


` 
 /**
     * Method to Get Device MAC Address For Ethernet 
     *
     * @return MAC Address as String
     */

    public String getEhernetDeviceMacAddress() {
        try {
              return loadFileAsString("/sys/class/net/eth0/address")
                  .toUpperCase().substring(0, 17);
          } catch (IOException e) {
              e.printStackTrace();
              return null;
          }
    }
`

i hope to be helpfull for some body 

thanks

**Comment by hypery2k** [comment]
the plugin is discontinued, so I will not maintain this repo anymore

**Comment by hypery2k** [comment]
won't update the plugin, as it's not maintained really anymore. Just make one last release from a PR. That's all
