### ISSUE TITLE
createHotspot and startHotspot issue

### ISSUE THREAD

**Issue by M-Summers** [hypery2k/cordova-hotspot-plugin#8]
Hi
Thankyou very much for your useful plugin.
createHotspot and startHotspot work well on my tablet with android 4.0, but they do not work on a mini pc      (connected to a TV) with android 4.4 (the error callback is called).
(The wifi is turned down though).

**Comment by hypery2k** [comment]
Did you get any error details?

**Comment by M-Summers** [comment]
Unfortunately no. 
I tried it on another mini PC with android 4.4.4 and it worked. 
I am not sure if it is worth checking and whether it is a problem of some devices or the plugin.

**Comment by hypery2k** [comment]
I've improved the error handling but I think it's a device issue
