### ISSUE TITLE
wifi is not connecting in ionic 3?

### ISSUE THREAD

**Issue by sudhan-ionic** [hypery2k/cordova-hotspot-plugin#81]
I am using  ionic framework for connecting wifi.
i am using this plugin 
```
$ ionic cordova plugin add cordova-plugin-hotspot
$ npm install --save @ionic-native/hotspot
```
I am using this Instance Members to connect.
```
this.hotspot.connectToWifi(SSID, password)
.then((data) => {

          console.log(".........hotspot..........",data);
        }, (error) => {
            console.log(".........hotspot error..........",error);
          })
```
But particular Wifi device is not connecting why?

I am having like this error
     .........hotspot.......... Connection was not successfull

**Comment by hypery2k** [comment]
the plugin is discontinued, so I will not maintain this repo anymore

**Comment by faizan1990** [comment]
Hi, can you let us know if there's an alternate that you or someone else is maintaining elsewhere?
