### ISSUE TITLE
Suddenly stopped working on device

### ISSUE THREAD

**Issue by shootdaj** [hypery2k/cordova-hotspot-plugin#85]
OS: Windows 10
Cordova Version: 4.5.2 (the Ionic NPM Package version, which I assume is the same as the Cordova version)
Android Version: 8.1.0

Steps to recreate: Call hotspot.scanWifi()

For some reason, the plugin just stopped working my test device which is a Samsung Note 8. When I scan the networks, it returns no networks. 

The WiFi list in Android works and returns all the networks, but when I use your plugin to scan inside my app, it returns no networks. It was working fine a few days ago. And it works on my other phone Google Pixel 2 XL. I restarted my phone, uninstalled the app, and reinstalled the app and reallowed the location permission, but still it returns no networks. Sounds like some setting got tripped at some point during my development and now it is not resetting. 

Anyone know any possible explanation for this issue? Thanks.

PS: I'm using the Ionic Hotspot plugin to include this in my Ionic app. It says on the page (https://ionicframework.com/docs/native/hotspot/) to submit issues to this repo.

**Comment by hypery2k** [comment]
the plugin is discontinued, so I will not maintain this repo anymore
