### ISSUE TITLE
Threading issue

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/cordova-hotspot-plugin#9]
I need to refresh the array (angularJS $scope) that holds the arp list.
But when I call "cordova.plugins.hotspot.getAllHotspotDevices" the device is "freezing" until the function resolved.

**Comment by webmaster-imaginet** [comment]
Thanks!
I see that the NPM version is still 0.7.0 is it correct?

**Comment by hypery2k** [comment]
I've release 0.7.1 in NPM
