### ISSUE TITLE
iOS support?

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [hypery2k/cordova-hotspot-plugin#93]
Hi,

I know you already answered this question (https://github.com/hypery2k/cordova-hotspot-plugin/issues/58), but things have changed on the iOS side: https://developer.apple.com/documentation/networkextension/nehotspotconfiguration

Can you please reconsider implementing iOS support?

Thanks,

Have a nice day

**Comment by ndvbd** [comment]
Same here. iOS support is needed.

@Yonn-Trimoreau, I see that these functions that you sent allow connecting to a network, but where are the functions to scan the available networks?

**Comment by Yonn-Trimoreau** [comment]
There is none for the moment.

A technical response from Apple: https://developer.apple.com/library/content/qa/qa1942/_index.html

**Comment by ndvbd** [comment]
Thanks Yonn, is there a any application out there in the App Store that does some wifi SSID scanning?

So basically from what you see it's possible to *create* a hotspot using the nehotspotconfiguration, but we can't scan for wifi hotspots?

**Comment by Yonn-Trimoreau** [comment]
I don't think so: [Apple banned Wifi scanner apps from the App Store](http://news.softpedia.com/news/After-Purging-Adult-Apps-Apple-Now-Pulls-Wi-Fi-Finders-136545.shtml)

I don't really know if you can create a hotspot. But you can connect to a hotspot (or any wifi network).

If you really need this functionality in your app, you should look into this cordova plugin: https://github.com/arsenal942/Cordova-Network-Manager

I think what proposes this plugin is all you can do with iOS for the moment: connect to wifi, disconnect from wifi.

**Comment by ndvbd** [comment]
Aha. So you can connect to a given SSID, but you can't know it exists before you try to connect to it, because you can't scan the SSIDs. Very strange.

**Comment by Yonn-Trimoreau** [comment]
Do you really feel the dumbness of Apple now? 'cause I'm feeling it deeply right now.. And sadly, this is far from the first time.

**Comment by ndvbd** [comment]
See also this: https://forums.developer.apple.com/thread/79603

**Comment by Yonn-Trimoreau** [comment]
Apple Staff: "Share and Enjoy" xD

**Comment by PaarthBarot** [comment]
This is really crazy, I mean providing this facility to developer team who is already sharing the purpose of scanning will not do any harm, ultimately we just need what devices are available! We are not going to change anything, then why the hell its restricted - I am sure they won't give the reason, as it's "Part of policy" bla bla bla! :(
