### ISSUE TITLE
How to get rate and delay of the current connection hotspot?

### ISSUE THREAD

**Issue by HZYou** [hypery2k/cordova-hotspot-plugin#97]
I want to get the rate and delay of the hotspot，I don't understand the meaning of your return the ping information.

I get the ping information : 
`
{  
   "requestTimeout":false,
   "stat":{  
      avg:"17.134",
      max:"67.707",
      min:"4.703",
      packetLoss:"0",
      stddev:"22.657",
      time:"33409"
   }
}
`

can you help me?

**Comment by hypery2k** [comment]
the plugin is discontinued.
