### ISSUE TITLE
ScanWifi() doesn't work on Android

### ISSUE THREAD

**Issue by MMartiDeveloper** [hypery2k/cordova-hotspot-plugin#98]
I'm trying to scan the Wi-Fi signals from my app to see which one is stronger. I followed the exact steps in the ionic documentation but the plugin seems that isn't working. 

This is my .ts file:

import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { Hotspot, HotspotNetwork } from '@ionic-native/hotspot';

/**
 * Generated class for the WifiSignalPage page.
 *
 * See https://ionicframework.com/docs/components/#navigation for more info on
 * Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: 'page-wifi-signal',
  templateUrl: 'wifi-signal.html',
})
export class WifiSignalPage {

  constructor(private hotspot: Hotspot, public navCtrl: NavController, public navParams: NavParams) {
  }

  goBack(){

  }

  startScan() {
    this.hotspot.scanWifi().then((networks: Array<HotspotNetwork>) => {
      console.log(networks);
      });
    }

  ionViewDidLoad() {
    console.log('ionViewDidLoad WifiSignalPage');
  }

}

When I try to emulate the application with the ionic app it says that the plugin is not installed, even when I do the

>  ionic cordova plugin add cordova-plugin-hotspot 

and the

> npm install --save @ionic-native/hotspot

So I'm being forced to build and emulate it on Android.

This is what the Android console shows:

<img width="742" alt="captura de pantalla 2018-08-20 a las 11 17 43" src="https://user-images.githubusercontent.com/25284561/44331884-fd6bf700-a46a-11e8-9ec2-098dc21fb085.png">

**Comment by curious-monggo** [comment]
Sad to see this discontinued

**Comment by webkhushboo** [comment]
scanWifi does not work for me on emulator . Please help how can I get connected wifi SSID name and unique id ?

**Comment by hypery2k** [comment]
the plugin is discontinued. 

BTW: Testing only works on real devices, not on emulator as in many case with Android

**Comment by shootdaj** [comment]
@hypery2k Do you happen to know if there is a good alternative since this is now discontinued?
